name: textos
description: Aplicativo para visualizar os textos do kalil e cria-los

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 5.1.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.11.0+1
  cached_network_image: ^0.8.0
  marquee: ^1.2.0
  shared_preferences: ^0.5.2
  firebase_messaging: ^5.0.1+1
  firebase_auth: ^0.11.0
  provider: ^2.0.0+1
  flutter_hsvcolor_picker: ^0.0.1
  transformer_page_view:
      path: ../transformer_page_view
  kalil_widgets:
      path: ../kalil_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Merriweather
      fonts:
        - asset: res/Merriweather-Regular.ttf
        - asset: res/Merriweather-Italic.ttf
          style: italic
        - asset: res/Merriweather-Light.ttf
          weight: 100
        - asset: res/Merriweather-Regular.ttf
          weight: 400
        - asset: res/Merriweather-Italic.ttf
          weight: 400
          style: italic
        - asset: res/Merriweather-Black.ttf
          weight: 500
        - asset: res/Merriweather-Bold.ttf
          weight: 700
    - family: Muli
      fonts:
        - asset: res/Muli-Regular.ttf
        - asset: res/Muli-Light.ttf
          weight: 100
        - asset: res/Muli-Regular.ttf
          weight: 400
        - asset: res/Muli-SemiBold.ttf
          weight: 500
        - asset: res/Muli-Bold.ttf
          weight: 700
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - res/baseline_lock_white_96dp.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
